### ISSUE TITLE
How to verify that the noisy data found is indeed noisy data?

### ISSUE THREAD

**Issue by guotong1988** [ChenglinYu/BHN#1]
I'm a newbie. Thank you very much!

**Comment by ChenglinYu** [comment]
收到

**Comment by guotong1988** [comment]
@ChenglinYu Thank you!

**Comment by guotong1988** [comment]
<img width="570" alt="image" src="https://github.com/ChenglinYu/BHN/assets/4702353/ad7c83c1-5cd7-42dd-9018-fad46dad6d82">
